### ISSUE TITLE
Same issue as ledcWrite()?

### ISSUE THREAD

**Issue by dannyz2** [pablomarquez76/AnalogWrite_ESP32#5]
I am using both a Servo, and PWM to control Backlight intensity. I have the servo on pin 13 , and the backlight on pin 15. The ESP32Servo Library siezes the Hardware timer, and thus has control of the same times needed for PWM. 
 I tried your library because it seemed from the ino provided that it would ot have this issue. It seems to suffer from the same problem, unless I have configured someting wrong/ Is it possible with your library to have both a fairly high frequency PWM, and the low frequency required for a servo, both in the same sketch?

**Comment by pablomarquez76** [comment]
Yes, the library suffers from that issue. It has to do with the way the timers are assigned. "analogWrite.h" file shows what timer uses each ledc channel. For example, channels 0,1,8,9 use timer 0, therefore they could have the same PWM frequency. The channels are assigned in sequential order from 0 to 15. So, if you want to use different frequencies you should initiate the PWM pins in pairs. I used this library for a robot that had 4 PWM pins to control motor speed and 2 pins to control servos. The motors worked at 5000Hz and the servos at 50Hz. The way I was able to make it work was initiating the motor pins first and then the servo pins, in that way the motor pins use channel 0,1,2,3 (timers 0 and 1) and the servos pins use channels 4 and 5 (timer 2). I hope this comment helps to solve this issue.

**Comment by pablomarquez76** [comment]
On the other hand, if you update you esp32 library to version 2.0.11 or later you will notice that analogWrite and tone function have been implemented. If you update your board, you no longer need this library and for servo you can use this function:
#define SERVO_FREQUENCY 50
#define SERVO_RESOLUTION 12
#define SERVO_MAX_ANGLE 180
#define SERVO_MIN_TICKS 102
#define SERVO_MAX_TICKS 512
#define SERVO_MIN_PULSE_WIDTH 498
#define SERVO_MAX_PULSE_WIDTH 2500
#define SERVO_OVERFLOW_PULSE_WIDTH 4000
void servoAttach(uint8_t pin) {
  analogWrite(pin, 0);
  uint8_t channel = analogGetChannel(pin);
  ledcSetup(channel, SERVO_FREQUENCY, SERVO_RESOLUTION);
}
void servo(uint8_t pin, uint16_t value) {
  uint8_t channel = analogGetChannel(pin);
  if (value < SERVO_MAX_ANGLE + 1) {
    ledcWrite(channel, map(value, 0, SERVO_MAX_ANGLE, SERVO_MIN_TICKS, SERVO_MAX_TICKS));  // 102:498ms 512:2500ms
  } else if (value < SERVO_OVERFLOW_PULSE_WIDTH) {
    ledcWrite(channel, map(value, SERVO_MIN_PULSE_WIDTH, SERVO_MAX_PULSE_WIDTH, SERVO_MIN_TICKS, SERVO_MAX_TICKS));  // map ms to ticks
  } else {
    ledcWrite(channel, 0);
  }
}

**Comment by dannyz2** [comment]
> Yes, the library suffers from that issue. It has to do with the way the timers are assigned. "analogWrite.h" file shows what timer uses each ledc channel. For example, channels 0,1,8,9 use timer 0, therefore they could have the same PWM frequency. The channels are assigned in sequential order from 0 to 15. So, if you want to use different frequencies you should initiate the PWM pins in pairs. I used this library for a robot that had 4 PWM pins to control motor speed and 2 pins to control servos. The motors worked at 5000Hz and the servos at 50Hz. The way I was able to make it work was initiating the motor pins first and then the servo pins, in that way the motor pins use channel 0,1,2,3 (timers 0 and 1) and the servos pins use channels 4 and 5 (timer 2). I hope this comment helps to solve this issue.

Yes, this helps a lot! Thanks! I read about the limitation in your readme, but, honestly it was very late, and I didn't understand how to invoke a workaround. Thanks to your comments, I now do.

> On the other hand, if you update you esp32 library to version 2.0.11 or later you will notice that analogWrite and tone function have been implemented. If you update your board, you no longer need this library and for servo you can use this function: #define SERVO_FREQUENCY 50 #define SERVO_RESOLUTION 12 #define SERVO_MAX_ANGLE 180 #define SERVO_MIN_TICKS 102 #define SERVO_MAX_TICKS 512 #define SERVO_MIN_PULSE_WIDTH 498 #define SERVO_MAX_PULSE_WIDTH 2500 #define SERVO_OVERFLOW_PULSE_WIDTH 4000 void servoAttach(uint8_t pin) { analogWrite(pin, 0); uint8_t channel = analogGetChannel(pin); ledcSetup(channel, SERVO_FREQUENCY, SERVO_RESOLUTION); } void servo(uint8_t pin, uint16_t value) { uint8_t channel = analogGetChannel(pin); if (value < SERVO_MAX_ANGLE + 1) { ledcWrite(channel, map(value, 0, SERVO_MAX_ANGLE, SERVO_MIN_TICKS, SERVO_MAX_TICKS)); // 102:498ms 512:2500ms } else if (value < SERVO_OVERFLOW_PULSE_WIDTH) { ledcWrite(channel, map(value, SERVO_MIN_PULSE_WIDTH, SERVO_MAX_PULSE_WIDTH, SERVO_MIN_TICKS, SERVO_MAX_TICKS)); // map ms to ticks } else { ledcWrite(channel, 0); } }

Yes, I was aware of this, but, thanks for the mention anyway. I would very much like to update to the latest ESP Library, but, I have many, many projects which were developed on 1.0.5, and even 1.0.6 breaks many of them. I know I should update anyway, but, with Arduino, it seems just about any update seems to break something, and, even if I updated everything today, and fixed all the resulting errors, I would then be stuck at that revision, as, likely any new updates would break stuff again.

I have installed VSCode & PlatformIO, and do any new developing there. PlatformIO takes care of the update issue, as you can specify what libraries the project can use, yet update the same libraries to use in new development, but old projects are unaffected. Definately NOT the case with Arduino.
